### ISSUE TITLE
Binance Data Fetcher 4h timeframe - Incorrect format: 4H 

### ISSUE THREAD

**Issue by alexcrownjr** [alpacahq/marketstore#202]
I tried to use binancefeeder with 4H timeframe and got error message "Incorrect format: 4H". 
```
My config file 
root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 30
stale_threshold: 5
enable_add: true
enable_remove: false
bgworkers:
  - module: binancefeeder.so
    name: BinanceFetcher
    config:
      base_timeframe: "4H"
      base_currency: "BTC"
      query_start: "2017-10-01 00:00"
```
When I used 1H timeframe everything was ok
