### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by reidlai** [alpacahq/marketstore#232]
Dear All,

I am newbie to use marketstore and built my docker image from source.  In my mkts.yml, i have this setting:
```
root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: false

triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      destinations:
        - 24H

bgworkers:
  - module: gdaxfeeder.so
    name: GdaxFetcher
    config:
      query_start: "2009-07-01 00:00"
      symbols:
        - BTC-USD
```

On the first day, everything works fine i can see historical data download from GDAXFeeder.  After few days, I suddenly got TLS handshare timeout from Coinbase.  How can i fix this issue or is this TLS cert issue?  Thanks for your help

```
marketstore_1  | {"level":"info","timestamp":"2019-07-06T01:18:41.637Z","msg":"1 destination(s) configured\n"}
marketstore_1  | {"level":"info","timestamp":"2019-07-06T01:18:41.637Z","msg":"InitializeTriggers - Done"}
marketstore_1  | {"level":"info","timestamp":"2019-07-06T01:18:41.637Z","msg":"InitializeBgWorkers"}
marketstore_1  | {"level":"info","timestamp":"2019-07-06T01:18:41.637Z","msg":"Trying to load module from path: /go/bin/gdaxfeeder.so...\n"}
marketstore_1  | {"level":"info","timestamp":"2019-07-06T01:18:41.653Z","msg":"Success loading module /go/bin/gdaxfeeder.so.\n"}
marketstore_1  | {"level":"error","timestamp":"2019-07-06T01:18:51.663Z","msg":"Failed to create bgworker: Get https://api.pro.coinbase.com/products: net/http: TLS handshake timeout"}
marketstore_1  | {"level":"info","timestamp":"2019-07-06T01:18:51.663Z","msg":"InitializeBgWorkers Done"}
marketstore_1  | {"level":"info","timestamp":"2019-07-06T01:18:51.663Z","msg":"enabling query access..."}
marketstore_1  | {"level":"info","timestamp":"2019-07-06T01:18:51.663Z","msg":"launching tcp listener for all services..."}
```
