### ISSUE TITLE
How do we use Polygon websockets using the plugin?

### ISSUE THREAD

**Issue by jaredmcqueen** [alpacahq/marketstore#263]
@Notargets 

According to the readme found [here](https://github.com/alpacahq/marketstore/tree/master/contrib/polygon), this is an example of how to configure the plugin:
```bgworkers:
  - module: polygon.so
    config:
        api_key: your_api_key
        base_url: https://api.polygon.io
        nats_servers: nats://nats1.polygon.io:30401, nats://nats2.polygon.io:30402, nats://nats3.polygon.io:30403
        symbols:
          - AAPL
          - SPY
```

Instead of using `nats_servers`, I'd like to use their websockets, specifically the alpaca one - `wss://alpaca.socket.polygon.io`.

Is the websockets endpont of `wss://alpaca.socket.polygon.io/` supported with this plugin?  If I can get it working, I will update add a pull request to update the documentation.  Many thanks alpacahq team.

**Comment by vinaygode** [comment]
Hi @jaredmcqueen -
Does it work if you add timezone, data_types, and replace base_url with ws_servers?
```
timezone: America/New_York
- module: polygon.so
    config:
        api_key: your_api_key
        ws_servers: wss://alpaca.socket.polygon.io
        data_types: [ 'bars' ]
        symbols:
          - AAPL
          - SPY
```
