### ISSUE TITLE
Trying to aggregate 1Sec data using `ondickagg.so` causes panic

### ISSUE THREAD

**Issue by goodboy** [alpacahq/marketstore#338]
This may relate to #201, #108, #128.

Using the following `mkts.yml` config:
```yaml
root_directory: data
listen_port: 5993
grpc_listen_port: 5995
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
stale_threshold: 5
enable_add: true
enable_remove: false

triggers:
  - module: ondiskagg.so
    on: "*/1Sec/TICK"
    config:
        # filter: "nasdaq"
        destinations:
            - 1Min
            - 5Min
            - 15Min
            - 1H
            - 1D

  - module: stream.so
    on: '*/*/*'
```

I get the following null deref from the server when trying to write `*/1Sec/TICK` data using the standard client:

```python
{'level': 'error',
 'msg': 'recovering from runtime error: invalid memory address or nil pointer '
        'dereference\n'
        'goroutine 175 [running]:\n'
        'runtime/debug.Stack(0xc0057f54e8, 0x11592a0, 0x1a90df0)\n'
        '\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\n'
        'github.com/alpacahq/marketstore/executor.fire.func1()\n'
        '\t/go/src/github.com/alpacahq/marketstore/executor/written.go:67 '
        '+0x70\n'
        'panic(0x11592a0, 0x1a90df0)\n'
        '\t/usr/local/go/src/runtime/panic.go:969 +0x166\n'
        'github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger.(*accumulator).apply(0x0, '
        '0x0, 0x12)\n'
        '\t'
        '/go/src/github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger/accum.go:276 '
        '+0x3c\n'
        'github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger.(*accumGroup).apply(0xc0003d9440, '
        '0x0, 0x12)\n'
        '\t'
        '/go/src/github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger/accum.go:39 '
        '+0x5f\n'
        'github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger.aggregate(0xc0057f5b10, '
        '0xc00049da50, 0x7f461728363b)\n'
        '\t'
        '/go/src/github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger/aggtrigger.go:310 '
        '+0x425\n'
        'github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger.(*OnDiskAggTrigger).writeAggregates(0xc00018c440, '
        '0xc00049da50, 0xc00049d940, 0x0, 0x0, 0xc0003d9140, 0xc0003ee000, '
        '0xa, 0x10, 0xc00018fced, ...)\n'
        '\t'
        '/go/src/github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger/aggtrigger.go:272 '
        '+0x6d7\n'
        'github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger.(*OnDiskAggTrigger).write(0xc00018c440, '
        '0xc00049d940, 0xc000533940, 0x0, 0xed6826025, 0x0, 0x0, 0xed6826025, '
        '0x0, 0xc0005337c0, ...)\n'
        '\t'
        '/go/src/github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger/aggtrigger.go:194 '
        '+0x267\n'
        'github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger.(*OnDiskAggTrigger).Fire(0xc00018c440, '
        '0xc000423f66, 0x16, 0xc0003c7ec0, 0x1, 0x1)\n'
        '\t'
        '/go/src/github.com/alpacahq/marketstore/contrib/ondiskagg/aggtrigger/aggtrigger.go:179 '
        '+0x66b\n'
        'github.com/alpacahq/marketstore/executor.fire(0x7f46173f0a60, '
        '0xc00018c440, 0xc000423f66, 0x16, 0xc0003c7ec0, 0x1, 0x1)\n'
        '\t/go/src/github.com/alpacahq/marketstore/executor/written.go:70 '
        '+0x8c\n'
        'created by github.com/alpacahq/marketstore/executor.run\n'
        '\t/go/src/github.com/alpacahq/marketstore/executor/written.go:57 '
        '+0x160\n',
 'timestamp': '2020-06-22T12:17:41.364Z'}
```

This would confirm that aggregating `1Sec` data is not yet supported?
