### ISSUE TITLE
Unable to load plugins when starting marketstore

### ISSUE THREAD

**Issue by bastulli** [alpacahq/marketstore#348]
Just installed MarketStore from source and I cannot load any of the plugins.  What steps am I missing?

1.  go get -u github.com/alpacahq/marketstore
2.  cd /work/src/github.com/alpacahq/marketstore
3.  make 
4.  make plugins
5.  $GOPATH/bin/marketstore init
6.  nano mkts.yml

=================================
```
root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: false
enable_last_known: false

triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      destinations:
        - 5Min
        - 15Min
        - 1H
        - 1D
bgworkers:
  - module: gdaxfeeder.so
    name: GdaxFetcher
    config:
      query_start: "2017-09-01 00:00"
```
=================================

7.  $GOPATH/bin/marketstore start

```
{"level":"info","timestamp":"2020-07-10T03:24:13.703Z","msg":"Running single threaded"}
{"level":"info","timestamp":"2020-07-10T03:24:13.704Z","msg":"using ./mkts.yml for configuration"}
{"level":"info","timestamp":"2020-07-10T03:24:13.704Z","msg":"Disabling \"enable_last_known\" feature until it is fixed..."}
{"level":"info","timestamp":"2020-07-10T03:24:13.704Z","msg":"initializing marketstore..."}
{"level":"info","timestamp":"2020-07-10T03:24:13.704Z","msg":"WAL Setup: initCatalog true, initWALCache true, backgroundSync true, WALBypass false: \n"}
{"level":"info","timestamp":"2020-07-10T03:24:13.704Z","msg":"Root Directory: data"}
{"level":"info","timestamp":"2020-07-10T03:24:13.706Z","msg":"My WALFILE: WALFile.1594351453704949204.walfile"}
{"level":"info","timestamp":"2020-07-10T03:24:13.713Z","msg":"launching rpc data server..."}
{"level":"info","timestamp":"2020-07-10T03:24:13.713Z","msg":"initializing websocket..."}
{"level":"info","timestamp":"2020-07-10T03:24:13.713Z","msg":"launching prometheus metrics server..."}
{"level":"info","timestamp":"2020-07-10T03:24:13.713Z","msg":"InitializeTriggers"}
{"level":"info","timestamp":"2020-07-10T03:24:13.714Z","msg":"triggerSetting = &{ondiskagg.so */1Min/OHLCV map[destinations:[5Min 15Min 1H 1D]]}"}
{"level":"info","timestamp":"2020-07-10T03:24:13.714Z","msg":"Trying to load module from path: bin/ondiskagg.so...\n"}
{"level":"error","timestamp":"2020-07-10T03:24:13.724Z","msg":"Unable to open plugin for trigger in ondiskagg.so: module ondiskagg.so not found in bin under any paths in GOPATH= or local directory\n: plugin.Open(\"ondiskagg\"): plugin was built with a different version of package go.uber.org/zap/buffer"}
{"level":"info","timestamp":"2020-07-10T03:24:13.724Z","msg":"InitializeTriggers - Done"}
{"level":"info","timestamp":"2020-07-10T03:24:13.724Z","msg":"InitializeBgWorkers"}
{"level":"info","timestamp":"2020-07-10T03:24:13.724Z","msg":"Trying to load module from path: bin/gdaxfeeder.so...\n"}
{"level":"error","timestamp":"2020-07-10T03:24:13.734Z","msg":"Unable to open plugin for bgworker in gdaxfeeder.so: module gdaxfeeder.so not found in bin under any paths in GOPATH= or local directory\n: plugin.Open(\"gdaxfeeder\"): plugin was built with a different version of package go.uber.org/zap/buffer"}
{"level":"info","timestamp":"2020-07-10T03:24:13.734Z","msg":"InitializeBgWorkers Done"}
{"level":"info","timestamp":"2020-07-10T03:24:13.734Z","msg":"enabling query access..."}
{"level":"info","timestamp":"2020-07-10T03:24:13.734Z","msg":"launching tcp listener for all services..."}
```
