### ISSUE TITLE
[polygon] csm write failure for key

### ISSUE THREAD

**Issue by yushihui** [alpacahq/marketstore#395]
{"level":"info","timestamp":"2020-11-20T01:44:37.473Z","msg":"authenticated successfully {feed:AM.AAPL}"}
{"level":"info","timestamp":"2020-11-20T01:44:37.473Z","msg":"authenticated successfully {feed:Q.AAPL}"}
{"level":"info","timestamp":"2020-11-20T01:44:37.480Z","msg":"subscribed {feed:Q.AAPL}"}
{"level":"info","timestamp":"2020-11-20T01:44:37.481Z","msg":"subscribed {feed:AM.AAPL}"}
{"level":"warn","timestamp":"2020-11-20T01:44:38.860Z","msg":"failed websocket connection, restarting... {subscription:AM.AAPL}"}
{"level":"error","timestamp":"2020-11-20T01:44:38.862Z","msg":"[polygon] csm write failure for key: [/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (/go/src/github.com/alpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
{"level":"info","timestamp":"2020-11-20T01:44:38.917Z","msg":"authenticated successfully {feed:AM.AAPL}"}
{"level":"info","timestamp":"2020-11-20T01:44:38.925Z","msg":"subscribed {feed:AM.AAPL}"}
{"level":"warn","timestamp":"2020-11-20T01:44:43.892Z","msg":"failed websocket connection, restarting... {subscription:Q.AAPL}"}
{"level":"error","timestamp":"2020-11-20T01:44:43.897Z","msg":"[polygon] failed to write csm (/go/src/github.com/alpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
{"level":"info","timestamp":"2020-11-20T01:44:43.954Z","msg":"authenticated successfully {feed:Q.AAPL}"}
{"level":"info","timestamp":"2020-11-20T01:44:43.962Z","msg":"subscribed {feed:Q.AAPL}"}
{"level":"warn","timestamp":"2020-11-20T01:44:45.957Z","msg":"failed websocket connection, restarting... {subscription:AM.AAPL}"}
{"level":"error","timestamp":"2020-11-20T01:44:45.958Z","msg":"[polygon] csm write failure for key: [/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (/go/src/github.com/alpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
{"level":"info","timestamp":"2020-11-20T01:44:46.016Z","msg":"authenticated successfully {feed:AM.AAPL}"}
{"level":"info","timestamp":"2020-11-20T01:44:46.024Z","msg":"subscribed {feed:AM.AAPL}"}

config

`
root_directory: data
listen_port: 5993
grpc_listen_port: 5995
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: false
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      destinations: [ '5Min', '15Min', '1H', '1D' ]
bgworkers:
  - module: polygon.so
    name: Polygon
    config:
      api_key: 'PK7CONO5L4KKKO9Z4PBC'
      base_url: https://api.polygon.io
      nats_servers: nats://nats1.polygon.io:30401, nats://nats2.polygon.io:30402, nats://nats3.polygon.io:30403
      data_types: [ 'bars', 'quotes' ]
      symbols:
        - AAPL
`

**Comment by yushihui** [comment]
I got this error,
 ```yaml
root_directory: data
listen_port: 5993
grpc_listen_port: 5995
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: false
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      destinations: [ '5Min', '15Min', '1H', '1D' ]
bgworkers:
  - module: polygon.so
    name: Polygon
    config:
      api_key: 'PK7CONO5L4KKKO9Z4PBC'
      base_url: https://api.polygon.io
      nats_servers: nats://nats1.polygon.io:30401, nats://nats2.polygon.io:30402, nats://nats3.polygon.io:30403
      data_types: [ 'bars', 'quotes' ]
      symbols:
        - AAPL

```

**Comment by mtucker502** [comment]
I also have seen this issue.

I am running the latest version of marketstore in a docker container:

```bash
root@1ff54d372ec6:/# marketstore --version
{"level":"info","timestamp":"2021-02-09T03:44:18.153Z","msg":"Running single threaded"}
version: latest
commit hash: 6fe1cf799a394469af860c60d2c058ae9bc16ee9
utc build time: 2021-02-05-00-28-41
```

Here is my config:

```yaml
bgworkers:
  - module: gdaxfeeder.so
    name: GdaxFetcher
    config:
      query_start: "2017-09-01 00:00"
      base_timeframe: 1Min
      symbols: [BTC-USD]
  - module: polygon.so
    name: Polygon
    config:
      api_key: ###omitted###
      #ws_servers: wss://alpaca.socket.polygon.io
      data_types: ["bars"]
      symbols:
        - AAPL
        - SPY
        - BB
        - AMC
```

It appears the websocket connects and as expected there isn't any data as it's currently after hours. However it doesn't appear that the Polygon plugin is able to create the necessary 

```
{"level":"info","timestamp":"2021-02-09T03:25:44.179Z","msg":"subscribing to upstream Polygon"}
{"level":"info","timestamp":"2021-02-09T03:25:44.179Z","msg":"enabling ... {scope:AM.AAPL,AM.SPY,AM.BB,AM.AMC}"}
{"level":"warn","timestamp":"2021-02-09T03:25:44.180Z","msg":"connection was already nil"}
{"level":"info","timestamp":"2021-02-09T03:25:44.260Z","msg":"authenticated successfully {feed:AM.AAPL,AM.SPY,AM.BB,AM.AMC}"}
{"level":"info","timestamp":"2021-02-09T03:25:44.262Z","msg":"subscribed {feed:AM.AAPL,AM.SPY,AM.BB,AM.AMC}"}
{"level":"error","timestamp":"2021-02-09T03:25:44.263Z","msg":"[polygon] csm write failure for key: [/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (/go/src/github.com/a
lpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
{"level":"error","timestamp":"2021-02-09T03:25:44.265Z","msg":"[polygon] csm write failure for key: [/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (/go/src/github.com/a
lpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
{"level":"error","timestamp":"2021-02-09T03:25:44.265Z","msg":"[polygon] csm write failure for key: [/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (/go/src/github.com/a
lpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
```
I also tested the same mkts.yml file with alpaca/marketstore:v4.1.0 and see the same error.
