### ISSUE TITLE
csm write failure for Polygon columns

### ISSUE THREAD

**Issue by mtucker502** [alpacahq/marketstore#430]
I am running the latest version of marketstore in a docker container:

```bash
root@1ff54d372ec6:/# marketstore --version
{"level":"info","timestamp":"2021-02-09T03:44:18.153Z","msg":"Running single threaded"}
version: latest
commit hash: 6fe1cf799a394469af860c60d2c058ae9bc16ee9
utc build time: 2021-02-05-00-28-41
```

Here is my config:

```yaml
bgworkers:
  - module: gdaxfeeder.so
    name: GdaxFetcher
    config:
      query_start: "2017-09-01 00:00"
      base_timeframe: 1Min
      symbols: [BTC-USD]
  - module: polygon.so
    name: Polygon
    config:
      api_key: ###omitted###
      #ws_servers: wss://alpaca.socket.polygon.io
      data_types: ["bars"]
      symbols:
        - AAPL
        - SPY
        - BB
        - AMC
```

It appears the websocket connects and as expected there isn't any data as it's currently after hours. However it doesn't appear that the Polygon plugin is able to create the necessary 

```
{"level":"info","timestamp":"2021-02-09T03:25:44.179Z","msg":"subscribing to upstream Polygon"}
{"level":"info","timestamp":"2021-02-09T03:25:44.179Z","msg":"enabling ... {scope:AM.AAPL,AM.SPY,AM.BB,AM.AMC}"}
{"level":"warn","timestamp":"2021-02-09T03:25:44.180Z","msg":"connection was already nil"}
{"level":"info","timestamp":"2021-02-09T03:25:44.260Z","msg":"authenticated successfully {feed:AM.AAPL,AM.SPY,AM.BB,AM.AMC}"}
{"level":"info","timestamp":"2021-02-09T03:25:44.262Z","msg":"subscribed {feed:AM.AAPL,AM.SPY,AM.BB,AM.AMC}"}
{"level":"error","timestamp":"2021-02-09T03:25:44.263Z","msg":"[polygon] csm write failure for key: [/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (/go/src/github.com/a
lpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
{"level":"error","timestamp":"2021-02-09T03:25:44.265Z","msg":"[polygon] csm write failure for key: [/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (/go/src/github.com/a
lpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
{"level":"error","timestamp":"2021-02-09T03:25:44.265Z","msg":"[polygon] csm write failure for key: [/1Min/OHLCV:Symbol/Timeframe/AttributeGroup] (/go/src/github.com/a
lpacahq/marketstore/catalog/catalog.go:104Category name does not match on-disk name)"}
```
I also tested the same mkts.yml file with alpaca/marketstore:v4.1.0 and see the same error.
