### ISSUE TITLE
[gdax] restarting marketstore restarts backfill

### ISSUE THREAD

**Issue by mtucker502** [alpacahq/marketstore#431]
I am running the latest version of marketstore in a docker container:

```bash
root@1ff54d372ec6:/# marketstore --version
{"level":"info","timestamp":"2021-02-09T03:44:18.153Z","msg":"Running single threaded"}
version: latest
commit hash: 6fe1cf799a394469af860c60d2c058ae9bc16ee9
utc build time: 2021-02-05-00-28-41
```

Here is my config:

```yaml
bgworkers:
  - module: gdaxfeeder.so
    name: GdaxFetcher
    config:
      query_start: "2017-09-01 00:00"
      base_timeframe: 1Min
      symbols: [BTC-USD]
  - module: polygon.so
    name: Polygon
    config:
      api_key: ###omitted###
      #ws_servers: wss://alpaca.socket.polygon.io
      data_types: ["bars"]
      symbols:
        - AAPL
        - SPY
        - BB
        - AMC
```

The backfill is complete and caught up:

```bash
(venv) root@ubuntu-s-1vcpu-1gb-nyc1-01:/var/data/config/mktsdb# date;docker logs mktsdb --since 30s
Tue Feb  9 04:09:04 UTC 2021
{"level":"info","timestamp":"2021-02-09T04:08:44.181Z","msg":"{subscription:AM.AAPL,AM.SPY,AM.BB,AM.AMC,channel_depth:0,handled_messages:0}"}
{"level":"info","timestamp":"2021-02-09T04:09:00.000Z","msg":"Requesting BTC-USD 2021-02-09 04:08:00 +0000 UTC - 2021-02-09 09:08:00 +0000 UTC"}
{"level":"info","timestamp":"2021-02-09T04:09:00.045Z","msg":"BTC-USD: 1 rates between 2021-02-09 04:08:00 +0000 UTC - 2021-02-09 04:08:00 +0000 UTC"}
{"level":"info","timestamp":"2021-02-09T04:09:00.048Z","msg":"next expected(2021-02-09 04:10:00 +0000 UTC) - now(2021-02-09 04:09:00.048930461 +0000 UTC m=+2596.207562967) = 59.951069539s"}
```

If I restart the container you can see the backfill starts again:

```
(venv) root@ubuntu-s-1vcpu-1gb-nyc1-01:/var/data/config/mktsdb# date;docker logs mktsdb --since 1s
Tue Feb  9 04:11:49 UTC 2021
{"level":"info","timestamp":"2021-02-09T04:11:48.005Z","msg":"BTC-USD: 300 rates between 2017-09-14 09:20:00 +0000 UTC - 2017-09-14 14:19:00 +0000 UTC"}
{"level":"info","timestamp":"2021-02-09T04:11:48.012Z","msg":"next expected(2017-09-14 14:21:00 +0000 UTC) - now(2021-02-09 04:11:48.012593978 +0000 UTC m=+21.647365090) = -29845h50m48.012593978s"}
{"level":"info","timestamp":"2021-02-09T04:11:48.013Z","msg":"Requesting BTC-USD 2017-09-14 14:20:00 +0000 UTC - 2017-09-14 19:20:00 +0000 UTC"}
{"level":"info","timestamp":"2021-02-09T04:11:48.084Z","msg":"BTC-USD: 300 rates between 2017-09-14 14:21:00 +0000 UTC - 2017-09-14 19:20:00 +0000 UTC"}
{"level":"info","timestamp":"2021-02-09T04:11:48.091Z","msg":"next expected(2017-09-14 19:22:00 +0000 UTC) - now(2021-02-09 04:11:48.091440552 +0000 UTC m=+21.726211647) = -29840h49m48.091440552s"}
```
