### ISSUE TITLE
Certs out of date on most crypto backfillers..

### ISSUE THREAD

**Issue by goodboy** [alpacahq/marketstore#586]
For eg. the [binance fetcher](https://github.com/alpacahq/marketstore/tree/master/contrib/binancefeeder) give this on startup with the container:

```sh
Requesting BTC 2018-01-01 00:00:00 +0000 UTC - 2018-01-01 05:00:00 +0000 UTC
Response error: Get "https://www.binance.com/api/v1/klines?endTime=1514782800000&interval=1m&startTime=1514764800000&symbol=BTCUSDT": x509: certificate signed by unknown authority
Problematic symbol BTC
```

same thing more or less with gdax and others..

**Comment by goodboy** [comment]
exact config:

```yaml
bgworkers:
  - module: binancefeeder.so
    name: BinanceFetcher
    config:
      symbols:
        - BTC
      base_timeframe: '1Min'
      base_currencies:
        - USDT
        # - BTC
      query_start: '2018-01-01 00:00'
```
