### ISSUE TITLE
Coinbase pro GDAX feeder crypto - Deprecated? 

### ISSUE THREAD

**Issue by brandoncamenisch** [alpacahq/marketstore#632]
IBeen using the bgworker for crypto data and it seems it might have quit working 😭

```
# Err message
 {"level":"info","timestamp":"2024-09-12T14:04:44.601Z","msg":"Response error: Coinbase Pro API is deprecated."}

# Config
bgworkers:
  - module: gdaxfeeder.so
    config:
      base_timeframe: '1Min'
      query_start: '2018-01-01 00:00'
      symbols:
        - BTC-USD
        - ETH-USD
        - LTC-USD
        - BCH-USD
        - ZRX-USD
        - ETC-USD
        - BAT-USD
```
